image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  # Пробуем несколько раз скачать зависимости
  - for i in {1..3}; do ./gradlew dependencies --refresh-dependencies && break || sleep 10; done

test_script:
  - java -jar ./artifacts/app-mbank.jar &
  - sleep 15
  - ./gradlew test --info

