image: Ubuntu2204
stack: jdk 11

branches:
  only:
    - main

build: off

cache:
  - '%USERPROFILE%\.gradle\caches'

install:
  - chmod +x gradlew
  # Умеренная очистка - только проблемных зависимостей
  - rm -rf ~/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/
  - rm -rf ~/.gradle/caches/modules-2/files-2.1/io.rest-assured/

  # Обновляем сертификаты (может помочь с SSL)
  - sudo apt-get update
  - sudo apt-get install -y ca-certificates

  # Скачивание зависимостей с подробным выводом
  - ./gradlew dependencies --refresh-dependencies --no-daemon --info

test_script:
  - java -jar ./artifacts/app-mbank.jar &
  - sleep 30
  - ./gradlew clean test --info --no-daemon