image: Ubuntu2204
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  # Полная очистка Gradle кеша
  - rm -rf ~/.gradle/caches/
  - rm -rf ~/.gradle/daemon/
  - rm -f ~/.gradle/gradle.properties

  # Очистка проекта
  - ./gradlew clean

  # Скачивание зависимостей с повторными попытками
  - for i in {1..3}; do ./gradlew dependencies --refresh-dependencies --no-daemon && break || sleep 15; done

test_script:
  - java -jar ./artifacts/app-mbank.jar &
  - sleep 25
  - ./gradlew test --info --no-daemon
