image: Ubuntu2004
stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  # Сначала даем Gradle скачать все зависимости
  - ./gradlew dependencies --refresh-dependencies

test_script:
  # Запускаем приложение в фоне
  - java -jar ./artifacts/app-mbank.jar &
  - sleep 10  # даем приложению время на запуск
  # Запускаем тесты
  - ./gradlew test --info
